25 correct clippy
psiayn/spressolisp pull request #29
Opened 2022-05-04 05:16 UTC by AugustoFKL

# Description

- Updating the code to follow the Clippy good practices. Used the command `cargo clippy --all-targets --all-features`

Fixes part of #25

## Type of change
- [X] Refactor

2022-05-04 05:16 UTC, AugustoFKL commented
@Samyak2 @psiayn sorry, can't ask review directly. If/when possible, please review!

2022-05-08 06:59 UTC, Samyak2 requested changes
Looks great, thanks!

A few comments though.

2022-05-08 06:59 UTC, Samyak2 commented on src/ast.rs
> -    }
Why was this removed?

2022-05-08 06:59 UTC, Samyak2 commented on src/ast.rs
> -    }
nvm, found it - https://rust-lang.github.io/rust-clippy/master/index.html#partialeq_ne_impl

2022-05-08 06:59 UTC, Samyak2 commented on src/eval/functions.rs
> +
What's this extra new line for?

2022-05-08 06:59 UTC, Samyak2 commented on benches/spresso_benchmark.rs
> -use criterion::{criterion_group, criterion_main, Criterion, BenchmarkId};
Would be better to comment out the whole file for now, instead of just the function bodies

2022-05-09 13:05 UTC, AugustoFKL commented on src/ast.rs
> -    }
Will mark as resolved. It is exactly the Partial Eq thing

2022-05-09 13:08 UTC, AugustoFKL commented on src/eval/functions.rs
> +
Unnecessary, will remove it!

2022-05-09 13:48 UTC, AugustoFKL commented
@Samyak2 done!

2022-05-10 17:04 UTC, Samyak2 approved these changes
LGTM. Thanks!

2022-05-10 17:06 UTC, Samyak2 commented
Looks like 6a75349ff403537ce122b27d88230d314144450b also fixed formatting (a part of #23), but that's ok

2022-05-10 17:06 UTC, merged